In [6]:
import numpy as np


In [7]:
zeros_vector = np.zeros(10)
print(zeros_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
memory_size = zeros_vector.size * zeros_vector.itemsize
print(memory_size)


80


In [9]:
help(np.add)


Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

In [10]:
range_vector = np.arange(10, 50)
print(range_vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
matrix_3x3 = np.reshape(np.arange(9), (3, 3))
print(matrix_3x3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
non_zero_indices = np.nonzero([1, 2, 0, 0, 4, 0])
print(non_zero_indices)


(array([0, 1, 4]),)


In [13]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
row_matrix = np.tile(np.arange(5), (5, 1))
print(row_matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [15]:
linspace_vector = np.linspace(0, 1, num=10, endpoint=False)[1:]
print(linspace_vector)


[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [16]:
random_vector = np.random.rand(10)
sorted_random_vector = np.sort(random_vector)
print(sorted_random_vector)


[0.00595682 0.0154585  0.03406547 0.11150335 0.30526142 0.50612149
 0.57458623 0.66974076 0.73481395 0.94800841]


In [17]:
print("int8:", np.iinfo(np.int8).min, np.iinfo(np.int8).max)
print("int32:", np.iinfo(np.int32).min, np.iinfo(np.int32).max)
print("int64:", np.iinfo(np.int64).min, np.iinfo(np.int64).max)
print("float32:", np.finfo(np.float32).min, np.finfo(np.float32).max)
print("float64:", np.finfo(np.float64).min, np.finfo(np.float64).max)


int8: -128 127
int32: -2147483648 2147483647
int64: -9223372036854775808 9223372036854775807
float32: -3.4028235e+38 3.4028235e+38
float64: -1.7976931348623157e+308 1.7976931348623157e+308


In [18]:
float_array = np.array([1.5, 2.7, 3.3])
int_array = float_array.astype(np.int32)
print(int_array)


[1 2 3]


In [19]:
row_mean_subtracted = matrix_3x3 - np.mean(matrix_3x3, axis=1, keepdims=True)
print(row_mean_subtracted)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [20]:
sorted_by_column = matrix_3x3[np.argsort(matrix_3x3[:, 1])]
print(sorted_by_column)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
matrix_3x3[[0, 1]] = matrix_3x3[[1, 0]]
print(matrix_3x3)


[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [22]:
C = np.array([2, 3, 1])
A = np.repeat(np.arange(len(C)), C)
print(A)


[0 0 1 1 1 2]
