In [1]:
import numpy as np

# Create the 5x5 matrix with random integers between 1 and 100
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)
print("Original Data:\n", data)


Original Data:
 [[66 47 19 80 88]
 [28 67 55 61 26]
 [ 7 48 15 87 49]
 [85 78 19 64 64]
 [60 73  9 44 88]]


In [2]:
# Swap the second (index 1) and fourth (index 3) rows
data[[1, 3]] = data[[3, 1]]
print("After Swapping Rows:\n", data)


After Swapping Rows:
 [[66 47 19 80 88]
 [85 78 19 64 64]
 [ 7 48 15 87 49]
 [28 67 55 61 26]
 [60 73  9 44 88]]


In [3]:
# Swap the second (index 1) and fourth (index 3) rows
data[[1, 3]] = data[[3, 1]]
print("After Swapping Rows:\n", data)


After Swapping Rows:
 [[66 47 19 80 88]
 [28 67 55 61 26]
 [ 7 48 15 87 49]
 [85 78 19 64 64]
 [60 73  9 44 88]]


In [4]:
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print("Normalized Data:\n", normalized_data)


Normalized Data:
 [[0.72839506 0.49382716 0.14814815 0.90123457 1.        ]
 [0.25925926 0.74074074 0.59259259 0.66666667 0.2345679 ]
 [0.         0.50617284 0.09876543 0.98765432 0.51851852]
 [0.96296296 0.87654321 0.14814815 0.7037037  0.7037037 ]
 [0.65432099 0.81481481 0.02469136 0.45679012 1.        ]]


In [5]:
z_score_data = (data - np.mean(data)) / np.std(data)
print("Z-Score Normalized Data:\n", z_score_data)


Z-Score Normalized Data:
 [[ 0.50401364 -0.23718289 -1.3294725   1.05015844  1.36224119]
 [-0.97837941  0.54302398  0.07489986  0.30896192 -1.0564001 ]
 [-1.79759662 -0.19817254 -1.48551387  1.32323084 -0.1591622 ]
 [ 1.24521016  0.97213775 -1.3294725   0.42599295  0.42599295]
 [ 0.26995158  0.77708604 -1.71957593 -0.35421392  1.36224119]]


In [6]:
# Reshape to a 1D array and split into 5 sub-arrays
flat_data = np.ravel(data)
split_arrays = np.split(flat_data, 5)
print("Split Arrays:\n", split_arrays)


Split Arrays:
 [array([66, 47, 19, 80, 88], dtype=int32), array([28, 67, 55, 61, 26], dtype=int32), array([ 7, 48, 15, 87, 49], dtype=int32), array([85, 78, 19, 64, 64], dtype=int32), array([60, 73,  9, 44, 88], dtype=int32)]


In [7]:
# Define two vectors
vec1 = np.array([3, 5, 6, 7, 8])
vec2 = np.array([2, 4, 6, 8, 10])
dot_product = np.dot(vec1, vec2)
print("Dot Product:", dot_product)


Dot Product: 198


In [8]:
# Create a new 3x3 matrix
data2 = np.random.randint(1, 100, size=(3, 3))

# Multiply the first 3x3 part of the data matrix with data2
result = np.dot(data[:3, :3], data2)
print("Matrix Multiplication Result:\n", result)


Matrix Multiplication Result:
 [[8603 3470 4473]
 [9151 7014 5425]
 [4744 2651 3160]]


In [9]:
# Create a 3x3 identity matrix and multiply by 2
identity_matrix = np.eye(3) * 2
inverse_matrix = np.linalg.inv(identity_matrix)
print("Inverse of 2x Identity Matrix:\n", inverse_matrix)


Inverse of 2x Identity Matrix:
 [[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.5]]


In [10]:
# Compute eigenvalues and eigenvectors for the first 3x3 part of the data
eigenvalues, eigenvectors = np.linalg.eig(data[:3, :3])
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues:
 [122.90705684  42.7708614  -17.67791824]
Eigenvectors:
 [[ 0.66377172  0.89484994  0.13694055]
 [ 0.66643866 -0.31402989 -0.57102342]
 [ 0.33950938 -0.31722045  0.80943162]]


In [12]:
import numpy as np

# Create the data matrix again as a float type so it can hold NaN values
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5).astype(float)

# Set 5 random elements to NaN
data_with_nan = data.copy()
nan_indices = np.random.choice(data.size, 5, replace=False)
data_with_nan[np.unravel_index(nan_indices, data.shape)] = np.nan
print("Data with Missing Values:\n", data_with_nan)

# Find indices of NaN values
nan_positions = np.where(np.isnan(data_with_nan))
print("NaN Indices:\n", nan_positions)



Data with Missing Values:
 [[26. 30. nan 51. 75.]
 [90. 94. nan 94. 29.]
 [57. 30. 18. 33.  1.]
 [nan 27. 64. 67. nan]
 [16. 54. 52. 89. nan]]
NaN Indices:
 (array([0, 1, 3, 3, 4]), array([2, 2, 0, 4, 4]))


In [13]:
# Replace NaNs with the mean of the data (ignoring NaNs)
mean_value = np.nanmean(data_with_nan)
data_with_nan[np.isnan(data_with_nan)] = mean_value
print("Data after Replacing NaNs with Mean:\n", data_with_nan)


Data after Replacing NaNs with Mean:
 [[26.   30.   49.85 51.   75.  ]
 [90.   94.   49.85 94.   29.  ]
 [57.   30.   18.   33.    1.  ]
 [49.85 27.   64.   67.   49.85]
 [16.   54.   52.   89.   49.85]]
